# Generated by Django 5.0.6 on 2024-07-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
