# Generated by Django 5.0.6 on 2024-07-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_download_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
