# Generated by Django 5.0.6 on 2024-07-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_series',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='parent_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
