# Generated by Django 5.0.6 on 2024-07-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_is_series_movie_parent_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_series',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='parent_code',
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('episode_number', models.IntegerField()),
                ('download_count', models.IntegerField(default=0)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.movie')),
            ],
        ),
    ]
