# Generated by Django 5.0.6 on 2024-07-24 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_is_series_remove_movie_parent_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='genre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='language',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='quality',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
