# Generated by Django 5.0.6 on 2024-07-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treyler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('treyler_id', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=10)),
            ],
        ),
    ]
